---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgAxfPFJaZMKG4zFIMlU1HkDub6ruuTf92fKfbeIusqVJTvRTFx978kjGN357+EEBxUEPNpJm9I4Jo51DYK0lTNPpf09gkb1mV/MObdVmZLdEWSKt8vs65lMDbMKBZvCCc3YLQ69EWd/cVzpuYZZH1OW2tkgJGy+i91WFVtuyDLGUTKC28CPg7OCAdUHcXzmCSP0KfZ9COO2+JLY7jfu93aDYG8LS56FDMHPzOTUZkqNdla2OQvmO0OzxBwyIFhMTXc0O+QbFxCTwg9/8y05rb+CQd1on5QsdAWKDSckSReRj2Nw/mxvEYIvyZd9WXn+FxC3GhZtRaB4AT/oiVNUELx97QAeVLpya0+o/8v5X1a/cQgHJPVOJyuUGCno76FYxdkUU4Ek4d5K+vSMCqrXASm4WQepn+55FRPBtwFogFOr+vYmF4Tkky6ENXj8t3J9eOQAn+RExdSdlm6q+gbv2eyFMvzDNda8m6WiNXLWMH5HfiQJ+z2oWU1LC4bvYDAikI5qtbKbj6S572XyLtOsS4jFy/MhuR7gKIF6l5NiGCkJ1QhcSX6NgrDiiecmIqMM2e031nEvcxrRpgCYHEb3W2qTll0kwoW+dzvpLqYzzG+A4kWVrSJa1ZK18elM9xmw7/2PrbMkJ6BOiDVeRrl1/Zs9OksALT7i8XAyJ6WK3Jc8YpuKYRXV6POU5a4uE/T1KP2LjWpsCLh6XQmACOgjgtax27SVnzbHFBT7Tqlux0IHXEOTDQwwtvI=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
